
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 22 16:00:24 CST 2018
//----------------------------------------------------

package DracoScript.Gramatica.Sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tSmash = 31;
  public static final int tString = 42;
  public static final int sMayorIgual = 11;
  public static final int tFor = 36;
  public static final int valId = 48;
  public static final int valDecimal = 51;
  public static final int valEntero = 49;
  public static final int tOval = 41;
  public static final int tPoint = 39;
  public static final int tWhile = 35;
  public static final int sAbreLlaves = 22;
  public static final int sDobleMas = 17;
  public static final int sIgual = 5;
  public static final int tLine = 44;
  public static final int tIf2 = 34;
  public static final int sDosPuntos = 3;
  public static final int sAbreParent = 18;
  public static final int sCierraCorchete = 21;
  public static final int tQuadrate = 40;
  public static final int valChar = 47;
  public static final int sMas = 27;
  public static final int sAbreCorchete = 20;
  public static final int tPrint = 37;
  public static final int EOF = 0;
  public static final int sPot = 24;
  public static final int sPor = 26;
  public static final int error = 1;
  public static final int tRunDasm = 43;
  public static final int sMenos = 29;
  public static final int sMenor = 8;
  public static final int valCadena = 50;
  public static final int sComa = 4;
  public static final int sMayor = 10;
  public static final int tIf = 32;
  public static final int sOr = 13;
  public static final int sPunto = 15;
  public static final int sModulo = 25;
  public static final int sNot = 14;
  public static final int sAnd = 12;
  public static final int tElif = 33;
  public static final int valFalse = 46;
  public static final int tRunMultDasm = 38;
  public static final int tVar = 30;
  public static final int sDiv = 28;
  public static final int valTrue = 45;
  public static final int sCierraLlaves = 23;
  public static final int sDiferenciacion = 7;
  public static final int sDobleMenos = 16;
  public static final int sMenorIgual = 9;
  public static final int sIgualacion = 6;
  public static final int sPuntoComa = 2;
  public static final int sCierraParent = 19;
}

