/* The following code was generated by JFlex 1.6.1 */

package Dasm.Gramatica.Lexico;

import Dasm.Gramatica.Sintactico.*;
import java_cup.runtime.*;
import Gui.Elementos.elementoGlobal;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>Lexer.jflex</tt>
 */
public class LexerDasm implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\10\1\3\1\2\1\0\1\3\1\1\16\10\4\0\1\3\1\0"+
    "\1\41\1\0\1\6\5\0\1\5\3\0\1\13\1\4\1\11\11\12"+
    "\7\0\1\14\1\33\1\35\1\15\1\30\1\17\1\27\1\7\1\16"+
    "\2\7\1\22\1\20\1\31\1\25\1\26\1\37\1\32\1\36\1\23"+
    "\1\21\1\24\3\7\1\40\1\0\1\42\2\0\1\34\1\0\1\14"+
    "\1\33\1\35\1\15\1\30\1\17\1\27\1\7\1\16\2\7\1\22"+
    "\1\20\1\31\1\25\1\26\1\37\1\32\1\36\1\23\1\21\1\24"+
    "\3\7\1\40\4\0\41\10\2\0\4\7\4\0\1\7\2\0\1\10"+
    "\7\0\1\7\4\0\1\7\5\0\27\7\1\0\37\7\1\0\70\7"+
    "\2\16\115\7\1\36\u0142\7\4\0\14\7\16\0\5\7\7\0\1\7"+
    "\1\0\1\7\21\0\160\10\5\7\1\0\2\7\2\0\4\7\10\0"+
    "\1\7\1\0\3\7\1\0\1\7\1\0\24\7\1\0\123\7\1\0"+
    "\213\7\1\0\5\10\2\0\236\7\11\0\46\7\2\0\1\7\7\0"+
    "\47\7\7\0\1\7\1\0\55\10\1\0\1\10\1\0\2\10\1\0"+
    "\2\10\1\0\1\10\10\0\33\7\5\0\3\7\15\0\5\10\6\0"+
    "\1\7\4\0\13\10\5\0\53\7\37\10\4\0\2\7\1\10\143\7"+
    "\1\0\1\7\10\10\1\0\6\10\2\7\2\10\1\0\4\10\2\7"+
    "\12\10\3\7\2\0\1\7\17\0\1\10\1\7\1\10\36\7\33\10"+
    "\2\0\131\7\13\10\1\7\16\0\12\10\41\7\11\10\2\7\4\0"+
    "\1\7\5\0\26\7\4\10\1\7\11\10\1\7\3\10\1\7\5\10"+
    "\22\0\31\7\3\10\104\0\1\7\1\0\13\7\67\0\33\10\1\0"+
    "\4\10\66\7\3\10\1\7\22\10\1\7\7\10\12\7\2\10\2\0"+
    "\12\10\1\0\7\7\1\0\7\7\1\0\3\10\1\0\10\7\2\0"+
    "\2\7\2\0\26\7\1\0\7\7\1\0\1\7\3\0\4\7\2\0"+
    "\1\10\1\7\7\10\2\0\2\10\2\0\3\10\1\7\10\0\1\10"+
    "\4\0\2\7\1\0\3\7\2\10\2\0\12\10\4\7\7\0\1\7"+
    "\5\0\3\10\1\0\6\7\4\0\2\7\2\0\26\7\1\0\7\7"+
    "\1\0\2\7\1\0\2\7\1\0\2\7\2\0\1\10\1\0\5\10"+
    "\4\0\2\10\2\0\3\10\3\0\1\10\7\0\4\7\1\0\1\7"+
    "\7\0\14\10\3\7\1\10\13\0\3\10\1\0\11\7\1\0\3\7"+
    "\1\0\26\7\1\0\7\7\1\0\2\7\1\0\5\7\2\0\1\10"+
    "\1\7\10\10\1\0\3\10\1\0\3\10\2\0\1\7\17\0\2\7"+
    "\2\10\2\0\12\10\1\0\1\7\17\0\3\10\1\0\10\7\2\0"+
    "\2\7\2\0\26\7\1\0\7\7\1\0\2\7\1\0\5\7\2\0"+
    "\1\10\1\7\7\10\2\0\2\10\2\0\3\10\10\0\2\10\4\0"+
    "\2\7\1\0\3\7\2\10\2\0\12\10\1\0\1\7\20\0\1\10"+
    "\1\7\1\0\6\7\3\0\3\7\1\0\4\7\3\0\2\7\1\0"+
    "\1\7\1\0\2\7\3\0\2\7\3\0\3\7\3\0\14\7\4\0"+
    "\5\10\3\0\3\10\1\0\4\10\2\0\1\7\6\0\1\10\16\0"+
    "\12\10\11\0\1\7\7\0\3\10\1\0\10\7\1\0\3\7\1\0"+
    "\27\7\1\0\12\7\1\0\5\7\3\0\1\7\7\10\1\0\3\10"+
    "\1\0\4\10\7\0\2\10\1\0\2\7\6\0\2\7\2\10\2\0"+
    "\12\10\22\0\2\10\1\0\10\7\1\0\3\7\1\0\27\7\1\0"+
    "\12\7\1\0\5\7\2\0\1\10\1\7\7\10\1\0\3\10\1\0"+
    "\4\10\7\0\2\10\7\0\1\7\1\0\2\7\2\10\2\0\12\10"+
    "\1\0\2\7\17\0\2\10\1\0\10\7\1\0\3\7\1\0\51\7"+
    "\2\0\1\7\7\10\1\0\3\10\1\0\4\10\1\7\10\0\1\10"+
    "\10\0\2\7\2\10\2\0\12\10\12\0\6\7\2\0\2\10\1\0"+
    "\22\7\3\0\30\7\1\0\11\7\1\0\1\7\2\0\7\7\3\0"+
    "\1\10\4\0\6\10\1\0\1\10\1\0\10\10\22\0\2\10\15\0"+
    "\60\7\1\10\2\7\7\10\4\0\10\7\10\10\1\0\12\10\47\0"+
    "\2\7\1\0\1\7\2\0\2\7\1\0\1\7\2\0\1\7\6\0"+
    "\4\7\1\0\7\7\1\0\3\7\1\0\1\7\1\0\1\7\2\0"+
    "\2\7\1\0\4\7\1\10\2\7\6\10\1\0\2\10\1\7\2\0"+
    "\5\7\1\0\1\7\1\0\6\10\2\0\12\10\2\0\4\7\40\0"+
    "\1\7\27\0\2\10\6\0\12\10\13\0\1\10\1\0\1\10\1\0"+
    "\1\10\4\0\2\10\10\7\1\0\44\7\4\0\24\10\1\0\2\10"+
    "\5\7\13\10\1\0\44\10\11\0\1\10\71\0\53\7\24\10\1\7"+
    "\12\10\6\0\6\7\4\10\4\7\3\10\1\7\3\10\2\7\7\10"+
    "\3\7\4\10\15\7\14\10\1\7\17\10\2\0\46\7\1\0\1\7"+
    "\5\0\1\7\2\0\53\7\1\0\u014d\7\1\0\4\7\2\0\7\7"+
    "\1\0\1\7\1\0\4\7\2\0\51\7\1\0\4\7\2\0\41\7"+
    "\1\0\4\7\2\0\7\7\1\0\1\7\1\0\4\7\2\0\17\7"+
    "\1\0\71\7\1\0\4\7\2\0\103\7\2\0\3\10\40\0\20\7"+
    "\20\0\125\7\14\0\u026c\7\2\0\21\7\1\0\32\7\5\0\113\7"+
    "\3\0\3\7\17\0\15\7\1\0\4\7\3\10\13\0\22\7\3\10"+
    "\13\0\22\7\2\10\14\0\15\7\1\0\3\7\1\0\2\10\14\0"+
    "\64\7\40\10\3\0\1\7\3\0\2\7\1\10\2\0\12\10\41\0"+
    "\3\10\2\0\12\10\6\0\130\7\10\0\51\7\1\10\1\7\5\0"+
    "\106\7\12\0\35\7\3\0\14\10\4\0\14\10\12\0\12\10\36\7"+
    "\2\0\5\7\13\0\54\7\4\0\21\10\7\7\2\10\6\0\12\10"+
    "\46\0\27\7\5\10\4\0\65\7\12\10\1\0\35\10\2\0\13\10"+
    "\6\0\12\10\15\0\1\7\130\0\5\10\57\7\21\10\7\7\4\0"+
    "\12\10\21\0\11\10\14\0\3\10\36\7\15\10\2\7\12\10\54\7"+
    "\16\10\14\0\44\7\24\10\10\0\12\10\3\0\3\7\12\10\44\7"+
    "\122\0\3\10\1\0\25\10\4\7\1\10\4\7\3\10\2\7\11\0"+
    "\300\7\47\10\25\0\4\10\u0116\7\2\0\6\7\2\0\46\7\2\0"+
    "\6\7\2\0\10\7\1\0\1\7\1\0\1\7\1\0\1\7\1\0"+
    "\37\7\2\0\65\7\1\0\7\7\1\0\1\7\3\0\3\7\1\0"+
    "\7\7\3\0\4\7\2\0\6\7\4\0\15\7\5\0\3\7\1\0"+
    "\7\7\16\0\5\10\32\0\5\10\20\0\2\7\23\0\1\7\13\0"+
    "\5\10\5\0\6\10\1\0\1\7\15\0\1\7\20\0\15\7\3\0"+
    "\33\7\25\0\15\10\4\0\1\10\3\0\14\10\21\0\1\7\4\0"+
    "\1\7\2\0\12\7\1\0\1\7\3\0\5\7\6\0\1\7\1\0"+
    "\1\7\1\0\1\7\1\0\4\7\1\0\13\7\2\0\4\7\5\0"+
    "\5\7\4\0\1\7\21\0\51\7\u0a77\0\57\7\1\0\57\7\1\0"+
    "\205\7\6\0\4\7\3\10\2\7\14\0\46\7\1\0\1\7\5\0"+
    "\1\7\2\0\70\7\7\0\1\7\17\0\1\10\27\7\11\0\7\7"+
    "\1\0\7\7\1\0\7\7\1\0\7\7\1\0\7\7\1\0\7\7"+
    "\1\0\7\7\1\0\7\7\1\0\40\10\57\0\1\7\u01d5\0\3\7"+
    "\31\0\11\7\6\10\1\0\5\7\2\0\5\7\4\0\126\7\2\0"+
    "\2\10\2\0\3\7\1\0\132\7\1\0\4\7\5\0\51\7\3\0"+
    "\136\7\21\0\33\7\65\0\20\7\u0200\0\u19b6\7\112\0\u51cd\7\63\0"+
    "\u048d\7\103\0\56\7\2\0\u010d\7\3\0\20\7\12\10\2\7\24\0"+
    "\57\7\1\10\4\0\12\10\1\0\31\7\7\0\1\10\120\7\2\10"+
    "\45\0\11\7\2\0\147\7\2\0\4\7\1\0\4\7\14\0\13\7"+
    "\115\0\12\7\1\10\3\7\1\10\4\7\1\10\27\7\5\10\20\0"+
    "\1\7\7\0\64\7\14\0\2\10\62\7\21\10\13\0\12\10\6\0"+
    "\22\10\6\7\3\0\1\7\4\0\12\10\34\7\10\10\2\0\27\7"+
    "\15\10\14\0\35\7\3\0\4\10\57\7\16\10\16\0\1\7\12\10"+
    "\46\0\51\7\16\10\11\0\3\7\1\10\10\7\2\10\2\0\12\10"+
    "\6\0\27\7\3\0\1\7\1\10\4\0\60\7\1\10\1\7\3\10"+
    "\2\7\2\10\5\7\2\10\1\7\1\10\1\7\30\0\3\7\2\0"+
    "\13\7\5\10\2\0\3\7\2\10\12\0\6\7\2\0\6\7\2\0"+
    "\6\7\11\0\7\7\1\0\7\7\221\0\43\7\10\10\1\0\2\10"+
    "\2\0\12\10\6\0\u2ba4\7\14\0\27\7\4\0\61\7\u2104\0\u016e\7"+
    "\2\0\152\7\46\0\7\7\14\0\5\7\5\0\1\7\1\10\12\7"+
    "\1\0\15\7\1\0\5\7\1\0\1\7\1\0\2\7\1\0\2\7"+
    "\1\0\154\7\41\0\u016b\7\22\0\100\7\2\0\66\7\50\0\15\7"+
    "\3\0\20\10\20\0\7\10\14\0\2\7\30\0\3\7\31\0\1\7"+
    "\6\0\5\7\1\0\207\7\2\0\1\10\4\0\1\7\13\0\12\10"+
    "\7\0\32\7\4\0\1\7\1\0\32\7\13\0\131\7\3\0\6\7"+
    "\2\0\6\7\2\0\6\7\2\0\3\7\3\0\2\7\3\0\2\7"+
    "\22\0\3\10\4\0\14\7\1\0\32\7\1\0\23\7\1\0\2\7"+
    "\1\0\17\7\2\0\16\7\42\0\173\7\105\0\65\7\210\0\1\10"+
    "\202\0\35\7\3\0\61\7\57\0\37\7\21\0\33\7\65\0\36\7"+
    "\2\0\44\7\4\0\10\7\1\0\5\7\52\0\236\7\2\0\12\10"+
    "\u0356\0\6\7\2\0\1\7\1\0\54\7\1\0\2\7\3\0\1\7"+
    "\2\0\27\7\252\0\26\7\12\0\32\7\106\0\70\7\6\0\2\7"+
    "\100\0\1\7\3\10\1\0\2\10\5\0\4\10\4\7\1\0\3\7"+
    "\1\0\33\7\4\0\3\10\4\0\1\10\40\0\35\7\203\0\66\7"+
    "\12\0\26\7\12\0\23\7\215\0\111\7\u03b7\0\3\10\65\7\17\10"+
    "\37\0\12\10\20\0\3\10\55\7\13\10\2\0\1\10\22\0\31\7"+
    "\7\0\12\10\6\0\3\10\44\7\16\10\1\0\12\10\100\0\3\10"+
    "\60\7\16\10\4\7\13\0\12\10\u04a6\0\53\7\15\10\10\0\12\10"+
    "\u0936\0\u036f\7\221\0\143\7\u0b9d\0\u042f\7\u33d1\0\u0239\7\u04c7\0\105\7"+
    "\13\0\1\7\56\10\20\0\4\10\15\7\u4060\0\2\7\u2163\0\5\10"+
    "\3\0\26\10\2\0\7\10\36\0\4\10\224\0\3\10\u01bb\0\125\7"+
    "\1\0\107\7\1\0\2\7\2\0\1\7\2\0\2\7\2\0\4\7"+
    "\1\0\14\7\1\0\1\7\1\0\7\7\1\0\101\7\1\0\4\7"+
    "\2\0\10\7\1\0\7\7\1\0\34\7\1\0\4\7\1\0\5\7"+
    "\1\0\1\7\3\0\7\7\1\0\u0154\7\2\0\31\7\1\0\31\7"+
    "\1\0\37\7\1\0\31\7\1\0\37\7\1\0\31\7\1\0\37\7"+
    "\1\0\31\7\1\0\37\7\1\0\31\7\1\0\10\7\2\0\62\10"+
    "\u1600\0\4\7\1\0\33\7\1\0\2\7\1\0\1\7\2\0\1\7"+
    "\1\0\12\7\1\0\4\7\1\0\1\7\1\0\1\7\6\0\1\7"+
    "\4\0\1\7\1\0\1\7\1\0\1\7\1\0\3\7\1\0\2\7"+
    "\1\0\1\7\2\0\1\7\1\0\1\7\1\0\1\7\1\0\1\7"+
    "\1\0\1\7\1\0\2\7\1\0\1\7\2\0\4\7\1\0\7\7"+
    "\1\0\4\7\1\0\4\7\1\0\1\7\1\0\12\7\1\0\21\7"+
    "\5\0\3\7\1\0\5\7\1\0\21\7\u1144\0\ua6d7\7\51\0\u1035\7"+
    "\13\0\336\7\u3fe2\0\u021e\7\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\10\36\0\140\10\200\0\360\10\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\2\1\2\3\15\1\1\4\1\5"+
    "\1\6\1\7\1\2\1\0\1\10\10\0\1\11\1\12"+
    "\2\0\1\13\4\0\1\14\2\0\1\15\1\16\1\17"+
    "\1\20\2\0\1\21\1\22\1\23\1\0\1\24\2\0"+
    "\1\25\1\26\1\27\1\0\1\30\1\0\1\31\1\32"+
    "\1\33\4\0\1\34\1\0\1\35\3\0\1\36\2\0"+
    "\1\37\2\0\1\40\14\0\1\41\4\0\1\42\1\0"+
    "\1\43\1\0\1\44\1\45";

  private static int [] zzUnpackAction() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\43\0\106\0\151\0\106\0\214\0\257\0\322"+
    "\0\365\0\u0118\0\u013b\0\u015e\0\u0181\0\u01a4\0\u01c7\0\u01ea"+
    "\0\u020d\0\u0230\0\u0253\0\u0276\0\u0299\0\u02bc\0\106\0\u02df"+
    "\0\106\0\u0302\0\u0325\0\u0348\0\u036b\0\322\0\u038e\0\u03b1"+
    "\0\u03d4\0\u03f7\0\u041a\0\u043d\0\u0460\0\u0483\0\106\0\u04a6"+
    "\0\u04c9\0\u04ec\0\u050f\0\u0532\0\u0555\0\u0578\0\u059b\0\u05be"+
    "\0\u05e1\0\106\0\106\0\106\0\106\0\u0604\0\u0627\0\u038e"+
    "\0\106\0\106\0\u064a\0\106\0\u066d\0\u0690\0\106\0\106"+
    "\0\106\0\u06b3\0\106\0\u06d6\0\106\0\106\0\106\0\u06f9"+
    "\0\u071c\0\u073f\0\u0762\0\106\0\u0785\0\106\0\u07a8\0\u07cb"+
    "\0\u07ee\0\106\0\u0811\0\u0834\0\106\0\u0857\0\u087a\0\106"+
    "\0\u089d\0\u08c0\0\u08e3\0\u0906\0\u0929\0\u094c\0\u096f\0\u0992"+
    "\0\u09b5\0\u09d8\0\u09fb\0\u0a1e\0\106\0\u0a41\0\u0a64\0\u0a87"+
    "\0\u0aaa\0\106\0\u0acd\0\106\0\u0af0\0\106\0\106";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\3\1\7\2\3\1\10"+
    "\1\11\1\3\1\12\1\13\1\3\1\14\1\15\1\3"+
    "\1\16\2\3\1\17\1\20\1\21\1\22\1\23\1\3"+
    "\1\24\1\3\1\25\1\26\2\3\1\27\1\3\1\30"+
    "\2\3\36\30\1\31\1\32\45\0\1\5\44\0\1\33"+
    "\1\34\43\0\2\35\4\0\25\35\13\0\2\36\1\37"+
    "\40\0\2\11\1\37\44\0\1\40\13\0\1\41\27\0"+
    "\1\42\45\0\1\43\42\0\1\44\3\0\1\45\40\0"+
    "\1\46\51\0\1\47\35\0\1\50\4\0\1\51\33\0"+
    "\1\52\4\0\1\53\43\0\1\54\5\0\1\55\30\0"+
    "\1\56\47\0\1\57\24\0\1\60\56\0\1\61\12\0"+
    "\1\30\2\0\36\30\25\0\1\62\5\0\1\63\1\64"+
    "\6\0\1\65\1\0\1\33\1\4\1\5\40\33\5\66"+
    "\1\67\35\66\6\0\5\35\1\0\25\35\13\0\2\70"+
    "\45\0\1\71\42\0\1\72\44\0\1\73\4\0\1\74"+
    "\47\0\1\75\33\0\1\76\35\0\1\77\55\0\1\100"+
    "\35\0\1\101\35\0\1\102\54\0\1\103\35\0\1\104"+
    "\34\0\1\105\65\0\1\106\25\0\1\107\53\0\1\110"+
    "\30\0\1\111\43\0\1\112\17\0\5\66\1\113\35\66"+
    "\4\0\1\5\1\67\54\0\1\114\60\0\1\115\30\0"+
    "\1\116\50\0\1\117\45\0\1\120\24\0\1\121\46\0"+
    "\1\122\54\0\1\123\6\0\4\66\1\5\1\113\35\66"+
    "\23\0\1\124\42\0\1\125\41\0\1\126\4\0\1\127"+
    "\32\0\1\130\45\0\1\131\4\0\1\132\31\0\1\133"+
    "\51\0\1\134\37\0\1\135\45\0\1\136\37\0\1\137"+
    "\45\0\1\140\52\0\1\141\32\0\1\142\52\0\1\143"+
    "\32\0\1\144\46\0\1\145\25\0\1\146\61\0\1\147"+
    "\23\0\1\150\61\0\1\151\31\0\1\152\34\0\1\153"+
    "\50\0\1\154\34\0\1\155\50\0\1\156\42\0\1\157"+
    "\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2835];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\21\1\1\11\1\1\1\11"+
    "\2\1\1\0\1\1\10\0\1\1\1\11\2\0\1\1"+
    "\4\0\1\1\2\0\4\11\2\0\1\1\2\11\1\0"+
    "\1\11\2\0\3\11\1\0\1\11\1\0\3\11\4\0"+
    "\1\11\1\0\1\11\3\0\1\11\2\0\1\11\2\0"+
    "\1\11\14\0\1\11\4\0\1\11\1\0\1\11\1\0"+
    "\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //Generando symbol para guardar el token encontrado

    StringBuffer string = new StringBuffer();

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }

    public elementoGlobal simbolo;
    public String nombreArchivo ="";
    public void iniciar(elementoGlobal simbolo, String nombreArchivo){
        this.simbolo=simbolo;
        this.nombreArchivo=nombreArchivo;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerDasm(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2868) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { //System.out.println("Error Lexico|token:" + yytext()+"| linea :"+yyline+ "| columna:"+ yycolumn);
                                        simbolo.tablaErrores.insertErrorLexical(nombreArchivo,yyline+1, yycolumn+1, "no se reconoce el token : "+yytext());
            }
          case 38: break;
          case 2: 
            { /* ignore */
            }
          case 39: break;
          case 3: 
            { return symbol(sym.valEntero,yytext())   ;
            }
          case 40: break;
          case 4: 
            { string.setLength(0); yybegin(STRING);
            }
          case 41: break;
          case 5: 
            { string.append( yytext() ); /*System.out.println("CierraComilla6"+ yytext());*/
            }
          case 42: break;
          case 6: 
            { yybegin(YYINITIAL); /*System.out.println("AbreComilla"+ yytext());*/
                                       return symbol(sym.valCadena, 
                                       string.toString());
            }
          case 43: break;
          case 7: 
            { string.append('\\');
            }
          case 44: break;
          case 8: 
            { return symbol(sym.valId,yytext());
            }
          case 45: break;
          case 9: 
            { return symbol(sym.tLt, yytext());
            }
          case 46: break;
          case 10: 
            { return symbol(sym.tOr, yytext());
            }
          case 47: break;
          case 11: 
            { return symbol(sym.tGt, yytext());
            }
          case 48: break;
          case 12: 
            { return symbol(sym.tBr, yytext());
            }
          case 49: break;
          case 13: 
            { string.append('\t');
            }
          case 50: break;
          case 14: 
            { string.append('\n');
            }
          case 51: break;
          case 15: 
            { string.append('\r');
            }
          case 52: break;
          case 16: 
            { string.append('\"');
            }
          case 53: break;
          case 17: 
            { return symbol(sym.valDecimal,yytext());
            }
          case 54: break;
          case 18: 
            { return symbol(sym.tAdd, yytext());
            }
          case 55: break;
          case 19: 
            { return symbol(sym.tAnd, yytext());
            }
          case 56: break;
          case 20: 
            { return symbol(sym.tDiv, yytext());
            }
          case 57: break;
          case 21: 
            { return symbol(sym.tMod, yytext());
            }
          case 58: break;
          case 22: 
            { return symbol(sym.tLte, yytext());
            }
          case 59: break;
          case 23: 
            { return symbol(sym.tPot, yytext());
            }
          case 60: break;
          case 24: 
            { return symbol(sym.tGte, yytext());
            }
          case 61: break;
          case 25: 
            { return symbol(sym.tEnd, yytext());
            }
          case 62: break;
          case 26: 
            { return symbol(sym.tEqz, yytext());
            }
          case 63: break;
          case 27: 
            { return symbol(sym.tNot, yytext());
            }
          case 64: break;
          case 28: 
            { return symbol(sym.tDiff, yytext());
            }
          case 65: break;
          case 29: 
            { return symbol(sym.tMult, yytext());
            }
          case 66: break;
          case 30: 
            { return symbol(sym.tCall, yytext());
            }
          case 67: break;
          case 31: 
            { return symbol(sym.tPrint, yytext());
            }
          case 68: break;
          case 32: 
            { return symbol(sym.tBrIf, yytext());
            }
          case 69: break;
          case 33: 
            { return symbol(sym.tFuncion, yytext());
            }
          case 70: break;
          case 34: 
            { return symbol(sym.tGet_local, yytext());
            }
          case 71: break;
          case 35: 
            { return symbol(sym.tSet_local, yytext());
            }
          case 72: break;
          case 36: 
            { return symbol(sym.tGet_global, yytext());
            }
          case 73: break;
          case 37: 
            { return symbol(sym.tSet_global, yytext());
            }
          case 74: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
