
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 09 01:41:43 CST 2018
//----------------------------------------------------

package D_plus.Gramatica.Sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tOvalo = 40;
  public static final int tImprimir = 37;
  public static final int sCierraLlave = 22;
  public static final int sMayorIgual = 11;
  public static final int tSino = 48;
  public static final int valId = 54;
  public static final int valDecimal = 57;
  public static final int tDetener = 33;
  public static final int valEntero = 55;
  public static final int tPunto = 38;
  public static final int tVacio = 46;
  public static final int tCaracter = 44;
  public static final int tMientras = 36;
  public static final int tNulo = 50;
  public static final int sIgual = 5;
  public static final int tEntero = 47;
  public static final int tImportar = 29;
  public static final int sCierraInterrogante = 16;
  public static final int sDosPuntos = 3;
  public static final int sAbreParent = 17;
  public static final int sCierraCorchete = 20;
  public static final int tSi = 35;
  public static final int tPrincipal = 31;
  public static final int sAbreLlave = 21;
  public static final int valChar = 53;
  public static final int tCuadrado = 39;
  public static final int sMas = 26;
  public static final int tLinea = 42;
  public static final int sAbreCorchete = 19;
  public static final int tEstructura = 30;
  public static final int EOF = 0;
  public static final int tContinuar = 34;
  public static final int sPot = 23;
  public static final int sPor = 25;
  public static final int error = 1;
  public static final int sMenos = 28;
  public static final int sMenor = 8;
  public static final int valCadena = 56;
  public static final int sComa = 4;
  public static final int tPara = 49;
  public static final int sMayor = 10;
  public static final int sOr = 13;
  public static final int sPunto = 15;
  public static final int sModulo = 24;
  public static final int sNot = 14;
  public static final int sAnd = 12;
  public static final int tCadena = 41;
  public static final int tBooleano = 45;
  public static final int valFalse = 52;
  public static final int tRetornar = 32;
  public static final int sDiv = 27;
  public static final int valTrue = 51;
  public static final int sDiferenciacion = 7;
  public static final int sMenorIgual = 9;
  public static final int sIgualacion = 6;
  public static final int sPuntoComa = 2;
  public static final int tDecimal = 43;
  public static final int sCierraParent = 18;
}

