
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 05 20:34:07 CST 2018
//----------------------------------------------------

package Dasm.Gramatica.Sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tMult = 4;
  public static final int tSet_local = 19;
  public static final int tDiv = 5;
  public static final int tAdd = 2;
  public static final int tBrIf = 16;
  public static final int tBr = 15;
  public static final int valCadena = 31;
  public static final int tEqz = 22;
  public static final int tGet_global = 18;
  public static final int tGet_local = 17;
  public static final int tDiff = 3;
  public static final int valEntero = 29;
  public static final int tFuncion = 23;
  public static final int tTee_local = 26;
  public static final int tMod = 6;
  public static final int tAnd = 13;
  public static final int valDecimal = 30;
  public static final int tLt = 8;
  public static final int EOF = 0;
  public static final int tOr = 14;
  public static final int tPrint = 25;
  public static final int tLte = 10;
  public static final int tTee_global = 27;
  public static final int tCall = 21;
  public static final int valId = 28;
  public static final int tSet_global = 20;
  public static final int error = 1;
  public static final int tNot = 12;
  public static final int tEnd = 24;
  public static final int tPot = 7;
  public static final int tGt = 9;
  public static final int tGte = 11;
}

